--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BagChaserENT/Mineconomy-PMMP
build-by-default: true
branches:
- main
projects:
  Mineconomy-PMMP:
    path: ""
    libs:
       - src: CortexPE/Commando/Commando
         version: ^3.2.1
    lint: false
...
